# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Comment.destroy_all
HikePhoto.destroy_all
HikeList.destroy_all
Hike.destroy_all
User.destroy_all

admin = User.create(name: 'Admin', username: 'Admin', password_digest:'123')

chim = Hike.create(title: 'Chimney Gulch', city: 'Golden', state: 'Colorado', difficulty:3, length:3, pet_friendly: true, directions: 'Access the trail via Lookout Mountain Road west of Highway 6 and roadside parking on Highway 6 eastbound from State Highway 58.', extra_info: 'The Front Range of Colorado touches three distinct ecosystems – grassland prairie, pinyon-ponderosa woodlands and montane – that support a rich variety of mammals, birds, amphibians and reptiles. Rabbit, hare, prairie dog, fox, coyote, badger, bobcat, mule deer, elk, black bear and mountain lion all call the Front Range their home.', user_id: admin.id)
HikePhoto.create(hike_id: chim.id, img_url: 'https://www.cityofgolden.net/wp-content/uploads/Chimney-Gulch.jpg', caption: 'Trail marker')
HikePhoto.create(hike_id: chim.id, img_url: 'http://3.bp.blogspot.com/-gFiX9wnY2RM/U3GWft3W5pI/AAAAAAAAFnk/9vkQUOSK3Jc/s1600/dsc05462-001.jpg', caption: 'View of Windy Saddle Park from the trail')

flvistas = Hike.create(user_id: admin.id, title: 'Flatirons Vista', city: 'Boulder', state: 'Colorado', difficulty: 1, length: 4, pet_friendly: true, directions: 'Head south on 19th street towards Arapahoe Ave. Turn right at the 1st cross street onto Arapahow Ave. Get onto CO-93 S and drive for a bout seven miles. The turn off will be on the right hand side of the road.', extra_info: 'While the most iconic views of the Flatirons are from the Chautauqua Trailhead, this trail south of town stands at a distance to the iconic formations, giving you unparalleled views of the whole mountain range. Equally great for trail runners and families, the open landscape of this trail (bring plenty of sunscreen) gives you a sense of scale and geography you won’t get on trails that lead directly into the foothills. Plus, for those who want a longer trek, plenty of connecting trails make it possible')
HikePhoto.create(hike_id: flvistas.id, img_url: 'https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_250,q_75,w_610/http://res.cloudinary.com/simpleview/image/upload/v1501535559/clients/boulder/6a133392_e220_4b17_a5a7_7b496e2d5c97_252618d3-1fa3-44a3-89ed-eb78e6802b31.jpg', caption: 'View at sunset')



 jfalls = Hike.create(user_id: admin.id, title: 'Judd Falls', city: 'Crested Butte', state: 'Colorado', difficulty: 1, length: 2, pet_friendly: false, directions: 'From Crested Butte, take Gothic Road (135) north past Mt. Crested Butte and the hamlet of Gothic. Just over the hill from Gothic is the parking lot and trailhead for Judd Falls/Copper Creek. You can begin walking from the parking lot up the dirt road, or high clearance vehicles can continue up the same road for another half mile to an upper parking lot. ', extra_info: 'Much of the trail crosses the property of the Rocky Mountain Biological Laboratory, which has posted some interpretive signs along the way. The beginning of the trail is rocky but overall is easy. Highly scenic views of Crested Butte and Gothic Mountain. The Copper Creek trail continues past the falls, and leads to the Maroon Bells-Snowmass. Wilderness Area where scenic trails connect to high mountain lakes, remote hot springs, and the Aspen area.')
 HikePhoto.create(hike_id: jfalls.id, img_url: 'https://i2.wp.com/crazyaboutcolorado.com/wp-content/uploads/2019/09/Untitled-design-8-copy-23.png?resize=940%2C788', caption: 'Sign at the trailhead')
 HikePhoto.create(hike_id: jfalls.id, img_url: 'https://i2.wp.com/crazyaboutcolorado.com/wp-content/uploads/2019/09/Untitled-design-8-copy-21.png?resize=940%2C788', caption: 'Judd Falls')
 HikePhoto.create(hike_id: jfalls.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/23953195/large_2a18873769ce6f9d128aa8260a18e425.jpg', caption: 'View on the trail')

 copper_creek = Hike.create(user_id: admin.id, title: 'Copper Creek Trail', city: 'Crested Butte', state: 'Colorado', difficulty: 3, length: 12, pet_friendly: false, directions: 'From Crested Butte, take Gothic Road (135) north past Mt. Crested Butte and the hamlet of Gothic. Just over the hill from Gothic is the parking lot and trailhead for Judd Falls/Copper Creek. You can begin walking from the parking lot up the dirt road, or high clearance vehicles can continue up the same road for another half mile to an upper parking lot.', extra_info: 'The Copper Creek Trail to Copper Lake is a 12 mile moderately trafficked out and back trail located near Crested Butte, Colorado that features a waterfall and is rated as moderate. This hike starts at the Judd Falls trailhead at Gothic Rd. It is a pretty forest hike that opens up in spots along Copper Creek to Copper Lake. The elevation gains are mild until the last few hundred yards. This route is closed to hiking during the winter months due to snow.')
 HikePhoto.create(hike_id: copper_creek.id, img_url: 'http://www.protrails.com/protrails/trails/Copper%20Lake%20-%20lake%20on%20descent%201.jpg', caption: 'Copper Lake')
 HikePhoto.create(hike_id: copper_creek.id, img_url: 'https://media-cdn.tripadvisor.com/media/photo-s/18/5f/21/d7/awesome-views.jpg', caption: 'Crested Butte from the trail')

 gal = Hike.create(user_id: admin.id, title: 'Mt. Galbraith', city: 'Golden', state: 'Colorado', difficulty: 3, length: 4, pet_friendly: true, directions: 'Take I-93 through Golden and turn onto Golden Gate Canyon Road. about two miles down the road on the left there is a well maintained gravel parking lot which marks the start of the trail.', extra_info: 'This beautiful hike follows the Cedar Gulch Trail and encircles Mount Galbraith with great views of Golden, Coors Plant and Denver. If you want to reach the peak, the elevation is just over 7200 feet. You will see interesting rock formations and lots of animal trails along the way. It can be narrow in places which makes passing difficult. Bikes are not allowed, this is a hiker-only trail.')
 HikePhoto.create(hike_id: gal.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40931992/extra_large_98800f3b887c3746fb3903169af5feb6.jpg', caption: 'the Rockies')
 HikePhoto.create(hike_id: gal.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40891986/extra_large_9efbe05be86e9e7fb92cb5112a9ef74a.jpg', caption: 'View from the peak of the trail')
 HikePhoto.create(hike_id: gal.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40854315/extra_large_f9512c3ad79253c29b4e504520c91714.jpg', caption: 'the beginning of the trail')

 chavez= Hike.create(user_id: admin.id, title: 'Chavez and Beaver Brook Trail Loop', city: 'Golden', state: 'Colorado', difficulty: 4, length: 5, pet_friendly: true, directions: 'Genesee Park is 20 miles west of Denver on I-70 to Exit 254 (Genesee Park Exit) or Exit 253 (Chief Hosa Exit). To get here, you’ll take the Chief Hosa Exit (Exit 253) and park in the parking lot on Stapleton Road to begin along the Beaver Brook Trail. There is an additional, smaller parking area just past the main lot where the Chavez Trail meets the road. From here, you can also choose to take the Braille Trail for a short stretch instead of the Chavez Trail.', extra_info: 'The route features a nice mix of elevation change and will have you walking alongside a creek for more than half of the loop. There are several stream crossings that have bridges to walk across. This shaded loop is especially great during summertime, as you can stop to take a swim along the way. During the fall, the leaves change into their gorgeous autumn colors. The left side of the loop is much gentler and wider, whereas the right route (the Chavez Trail) is steeper with a few ledges to maneuver and is steep and rocky.')
 HikePhoto.create(hike_id: chavez.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/29605732/extra_large_3d6ce3c1064141503013c5b41d9a1e88.jpg', caption: 'View from the trail')
 HikePhoto.create(hike_id: chavez.id, img_url: 'https://www.10adventures.com/wp-content/uploads/2018/10/Denver_01-BeaverBrook_13_UpRiverView.jpg', caption: 'Beaver Brook')


 rainbow = Hike.create(user_id: admin.id, title: 'RainBow Lakes', city: 'Indian Peaks Wilderness', state: 'Colorado', difficulty: 2, length: 3, pet_friendly: true, directions: 'From Nederland, head north on Colorado Highway 72 for approximately seven miles. Look for the University of Colorado Mountain Research Station sign and turn west onto National Forest System Road 298.', extra_info: ' This trail leads to three small lakes in the scenic Indian Peaks Wilderness. It’s not as heavily traveled as nearby trails, perhaps because of the road, which is rocky and has potholes but is passable to passenger cars. Still, it’s worth the trip.')
 HikePhoto.create(hike_id: rainbow.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/27574067/large_170dd9ec86c10151254450b7b8195adc.jpg', caption: 'Lake view')
 HikePhoto.create(hike_id: rainbow.id, img_url: 'https://www.fs.usda.gov/Internet/FSE_MEDIA/stelprdb5375675.jpg', caption: 'Trailhead')
 

 mitchell = Hike.create(user_id: admin.id, title: 'Mitchell Lake Trail', city: 'Indian Peaks Wilderness', state: 'Colorado', difficulty: 2, length: 5, pet_friendly: true, directions: 'From Colorado Highway 72 at Ward, turn west onto the Brainard Lake Road. Travel 2.5 miles to the entrance portal, and continue another three miles to Mitchell Creek Trailhead.', extra_info: 'A very popular and scenic trail. It leads to Blue Lake at 11,300 feet, with views of surrounding high peaks. The trailhead is closed in winter - often until mid-June - due to snow, but can be accessed on skis or snowshoes from the closure point further down the road. Entrance fee or permit required.')
 HikePhoto.create(hike_id: mitchell.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/11294454/large_8aafb124f5cf30bac2e561f119c3ba53.jpg', caption: 'A view from the trail')
 HikePhoto.create(hike_id: mitchell.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/28564807/large_3f1c6a1b2744249ef5f52c4ff08b0352.jpg', caption: 'Blue Lake via Mitchell Lake Trail')
 HikePhoto.create(hike_id: mitchell.id, img_url: 'https://www.fs.usda.gov/Internet/FSE_MEDIA/stelprdb5323419.jpg', caption: 'On the trail')


 walker = Hike.create(user_id: admin.id, title: 'Walker Ranch Loop', city: 'Boulder', state: 'Colorado', difficulty: 4, length: 8, pet_friendly: true, directions: 'Starting in the center of Boulder, head south on 19th street towards Arapahoe Ave. Turn right at the 1st cross street onto Arapahow Ave, then in 1 mile turn left onto 9th street. Turn right on to Baseline road in half a mile and then continue onto Flagstaff road for 7 miles. The turnoff to the trailhead will ne on the left hand side.', extra_info: 'Walker Ranch Loop is a fantastic hiking and mountain biking trail through Walker Ranch Park and a portion of El Dorado Canyon State Park. The loop can be done in either direction. Going clockwise from the Walker Ranch Parking Access, the trail starts downhill then offers a nice climb that opens up at the top at the Crescent Meadows Trailhead parking area. From here it’s a two mile descent followed by a short portion down very steep steps, followed by another moderate climb back to the trailhead. The trail is primarily gravel and loose dirt. The loop offers great scenic views and a beautiful river. ')
 HikePhoto.create(hike_id: walker.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/33595170/extra_large_52bca2f4ae624998b2a084fb21507228.jpg', caption: 'South Boulder Creek via Walker Ranch Trail')
 HikePhoto.create(hike_id: walker.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40925310/extra_large_a546f274d955a2736bc9598cb9c9519b.jpg', caption: 'Walker Ranch Loop')
 HikePhoto.create(hike_id: walker.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40925222/extra_large_7af76a82f79dcc8194c6914d9b4661b1.jpg', caption: 'The Rockies from the trail')

 bear=Hike.create(user_id: admin.id, title: 'Bear Peak via Shanahan Ridge', city: 'Boulder', state: 'Colorado', difficulty: 5, length: 5, pet_friendly: true, directions: 'From Hwy 93/Broadway in Boulder, go west at the light for Greenbriar Boulevard. There are a few trailheads tucked in the neighborhood.', extra_info: 'This hike can be completed year round, though it can be covered in snow after a snowfall. Depending on the time of year, there are creeks and ponds for water.')
 HikePhoto.create(hike_id: bear.id, img_url: 'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzk5NTM2MzEvNjg1MTJiMWE4ZDI2NDM2Y2ZiMzMzMTEyY2FmMGYwYjMuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==', caption: 'Bear Peak')
 HikePhoto.create(hike_id: bear.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40960606/extra_large_30198f0e16eb9ac071b903e40037975f.jpg', caption: 'View from the top')
 HikePhoto.create(hike_id: bear.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40643599/extra_large_49c61054f4c6173d69665251807ba56f.jpg', caption: 'Interesting find on the trail')

 grnmtn = Hike.create(user_id: admin.id, title: 'Green Mountain Loop via Chautaqua Trail', city: 'Boulder', state: 'Colorado', difficulty: 5, length: 6, pet_friendly: true, directions: 'In Boulder, travel west on Baseline from Broadway. After about 1 mile, turn south on Kinnikinic Rd and park at trailhead. This is a busy place in summer, you might have to park on Baseline Rd.', extra_info: 'A popular peak hike providing views of the Indian Peaks and Boulder that features beautiful wild flowers in the spring and summer. ')
 HikePhoto.create(hike_id: grnmtn.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41035629/extra_large_a15463a6934b4c4aed82abe9608b4e81.jpg', caption: 'Looking down at Boulder')
 HikePhoto.create(hike_id: grnmtn.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41035606/extra_large_c28eb3f87213da55041a27f5cbff3e47.jpg', caption: 'View of the Flatirons')
 HikePhoto.create(hike_id: grnmtn.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40830506/extra_large_4c3941e27cb3c949224c0e6e3e1ebe3a.jpg', caption: 'Trail vibes')


 lion = Hike.create(user_id: admin.id, title: `Lion's Lair Spur Trail`, city: 'Boulder', state: 'Colorado', difficulty: 2, length: 4, pet_friendly: true, directions: 'Starting on Boradway, you will head North for about half a mile and the turn left onto Mapleton Ave. From there just continue onto Sunshine Canyon Drive for 2 miles and the trailhead will be on your right.', extra_info: 'Very heavily trafficked on weekends, this well-maintained single-track trail is mostly through an evergreen forest.')
 HikePhoto.create(hike_id: lion.id, img_url: 'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMjMxNjYxODkvZjRiODczN2NlOWY5MWE2ZDU3YTE4YzFkYjVkMGQwMzcuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==', caption: 'On the trail')

 sanitas = Hike.create(user_id: admin.id, title: 'Mount Sanitas and Sanitas Valley Loop', city: 'Boulder', state: 'Colorado', difficulty: 5, length: 3, pet_friendly: true, directions: 'Directions from Broadway: Traveling north, pass the University then turn left on to Mapleton Avenue. The trailhead lies approximately seven blocks west of Broadway.', extra_info: 'Mount Sanitas is a must-do hike if you’re in Boulder. You can basically walk to the Centennial Trailhead on Sunshine Canyon Drive from downtown Boulder. The peak offers beautiful views, with enough challenge to get you sweating. The trailhead has a small parking area that gets full quickly in the morning, so it’s best to arrive early. If it’s full, there is more parking down the road. From the trailhead, continue north on Mount Sanitas Trail. This trail has a steady incline along a rocky, sometimes washed out trail. Sturdy boots are recommended. Eventually you’ll reach the summit of Mount Sanitas. Enjoy the view of Boulder, and the mountains to the north and west. From here, you can either complete the mapped loop on this page, or simply return the way you came.')
 HikePhoto.create(hike_id: sanitas.id, img_url: 'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMTk4MDM0OTcvZTQ2MTA5MzRjYWY3MjY4MDVmNDFiZWYyMmFiZGY2MTIuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==', caption: 'Mount Sanitas')
 HikePhoto.create(hike_id: sanitas.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41036997/extra_large_1927f3c0e529cc545a1b3c834c96214e.jpg', caption: 'Looking down at Boulder')


 huron = Hike.create(user_id: admin.id, title: 'Huron Peak via North Huron Trail', city: 'Buena Vista', state: 'Colorado', difficulty: 4, length: 7, pet_friendly: true, directions: 'From Buena vista take US-24 W for 15 miles, then turn left onto Co Rd 390. Take that for 12 miles and then make another left onto Forest Rd 390.', extra_info: `One of Colorado's 14ers. Great, easy to follow trail. Need 4x4 to get to the top trailhead.`)
 HikePhoto.create(hike_id: huron.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40982865/extra_large_957e69080390c3fb34f7887feaec878a.jpg', caption: '')
 HikePhoto.create(hike_id: huron.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40982863/extra_large_6fd57b4f3c190f07387126ecc0c0fce0.jpg', caption: 'Going up')
 HikePhoto.create(hike_id: huron.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40982864/extra_large_b7a62466ee67f5de641f829232e2889e.jpg', caption: 'Huron Peak')

 yale=Hike.create(user_id: admin.id, title: 'Mount Yale Summit Trail', city: 'Buena Vista', state: 'Colorado', difficulty: 5, length: 10, pet_friendly: true, directions: 'From the town of Buena Vista, head west from the stoplight( Main Street or 306),which turns to Cottonwood Pass, then go to the Denny Creek trailhead.', extra_info: 'From the fork, the trail is fairly easy up until around 13,000 feet. From here follow the switchbacks up to the saddle around 13,900. This area is steep and probably the most demanding part of the hike. Once you reach the saddle you have about 300 more feet of elevation gain which requires class 2 scrambling with options of class 3.')
 HikePhoto.create(hike_id: yale.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/10085586/extra_large_2a656063a78eb0b73435c45333b53518.jpg', caption: 'Mount Yale')
 HikePhoto.create(hike_id: yale.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41025434/extra_large_6ed5892a786d94416b7d4b22d60e8457.jpg', caption: 'From the lower section of the trail')


 kroenke = Hike.create(user_id: admin.id, title: 'Kroenke Lake Trail', city: 'Buena Vista', state: 'Colorado', difficulty: 3, length: 9, pet_friendly: true, directions: 'From Main St. in Buena Vista, go west to North Creek Rd., turn right and follow it to the trailhead.', extra_info: ' Dogs are also able to use this trail but must be kept on leash.')
 HikePhoto.create(hike_id: kroenke.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40545644/extra_large_2f61068cc771b517cdd9533494558a68.jpg', caption: 'Kroenke Lake')
 

 bearlake = Hike.create(user_id: admin.id, title: 'Bear Lake via Horn Fork Trail', city: 'Buena Vista', state: 'Colorado', difficulty: 4, length: 11, pet_friendly: true, directions: 'From the Stoplight in Buena Vista head north on highway 24 to Crossman Avenue and take left.  Follow Crossman until you come to a T in the road.  Turn right.  The road will soon curve left and then back right.  When it curves right there is a sharp left for County road 365.  Take County road 365 to its end at the parking lot for North Cottonwood Trailhead.', extra_info: 'A high altitude lake with views of many mountains. From the trailhead follow the obvious path west along North Cottonwood Creek.  After a mile and a half the trail will cross to the north side of the stream and take you into the Horn Fork Basin along Horn Fork Creek.  The trail is well traveled and easy to follow.  As you near treeline there are many established camping sites and this trip makes a great overnighter.  About 3/4 of a mile after treeline you will come to an intersection labeled for Bear Lake.  Take the trail to the Left and follow it a short distance to the Lake.')
 HikePhoto.create(hike_id: bearlake.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/39026511/large_b61dcbbfe00be8c25b4115ed7f53c834.jpg', caption: 'Bear Lake')
 HikePhoto.create(hike_id: bearlake.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41032452/extra_large_126038deae5eb1c9de442f2f3c5370cf.jpg', caption: 'View on the hike up')
 HikePhoto.create(hike_id: bearlake.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/30148722/extra_large_5947f8941a593c2f45df420701bde193.jpg', caption: 'Trail sign')

 muscoco= Hike.create(user_id: admin.id, title: 'Mount Muscoso Trail', city: 'Colorado Springs', state: 'Colorado', difficulty: 3, length: 4, pet_friendly: true, directions: 'The trailhead can be reached from Interstate 25 by taking Exit 140. Then take Tejon Street to Cheyenne Boulevard until you reach North Cheyenne Cañon. There will be parking by the trailhead on the left.', extra_info: `This very well-marked and well-maintained popular trail in Colorado Springs can be challenging but the breathtaking views are worth it. In one direction you will see the mountains and in the other you see Colorado Springs for miles and even the wind mills in the distance. It's a pretty easy hike except for the last half mile to the summit of Mount Muscoco is extra steep. Definitely recommend hiking boots over sneakers because of the loose gravel. The route starts at the Mount Cutler/Mount Muscoco Trailhead along N Cheyenne Canyon Road. You'll go southeast along the Mount Cutler Trail for about a mile, before turning right onto the Mount Muscoco Trail.`)
 HikePhoto.create(hike_id: muscoco.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40990054/extra_large_50eb2b4df6593e57223aa6ad53b12c96.jpg', caption: 'Mountain vies')
 HikePhoto.create(hike_id: muscoco.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40990060/extra_large_c145ce7fec2e5a91be7cd086b7c0ae7a.jpg', caption: 'Looking down at Colorado Springs')
 HikePhoto.create(hike_id: muscoco.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40975873/extra_large_a2c3bf6301f8975766713de5f6dfb16a.jpg', caption: 'Wow')

 gog=Hike.create(user_id: admin.id, title: 'Palmer, Buckskin-Charley, Niobrara, and Bretag Trail Loop', city: 'Colorado Springs', state: 'Colorado', difficulty: 1, length: 4, pet_friendly: true, directions: 'From I-25 S take exit 146 for Garden of the Gods Rd. Then keep right at the fork and follow the signs for Colorado Tech/Rusina Rd and then merge onto Garden of the Gods Rd. Follow this to your destination', extra_info: `This loop trail takes you on a walk around the main section of the formations that constitute the Garden of the Gods as most people experience it. Three primary trails connect to form a 4 mile loop: The Palmer Trail begins on the north side of the main parking area, heading west and then south. After a little more than a mile, a short 400 yard trail branches off to the Siamese Twins formation. Returning to the main trail, you'll cross the road and cut through the main park area's southern section on the Buckskin Charley Trail. When this reaches the other side of the paved road loop, you'll cross again, this time heading for the Ute Trail, which eventually runs north to join with the Susan Breitag trail, and on back to the start point. If this sounds confusing, don't worry. The large formations in the center of the park are visible from all parts of the trail. Just keep circling them.`)
 HikePhoto.create(hike_id: gog.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/23505495/extra_large_1edf304ed943b129ba3c98cac5b4d6b2.jpg', caption: '')
 HikePhoto.create(hike_id: gog.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40933226/extra_large_db6eded29c08e436600a04aae361167c.jpg', caption: '')

 helen=Hike.create(user_id: admin.id, title: 'Helen Hunt Falls', city: 'Colorado Springs', state: 'Colorado', difficulty: 1, length: 1, pet_friendly: true, directions: 'Take the Nevada Exit off of I-25 on the South side of Colorado Springs.  Follow Nevada south a few blocks to Cheyenne Blvd.  Turn West on Cheyenne Blvd.  Continue on this road until you reach a fork in the road with a sign for Helen Hunt falls to the right and Seven Falls to the left.  This will take you into Cheyenne Canyon.  Follow this curvy road until you get to the vistors station at a large switchback in the road.  Park here.', extra_info: 'Helen Hunt Falls named after Helen Hunt Jackson, author and social activist in the late 19th century  marks the abrupt descent of Cheyenne Creek where North Cheyenne Canyon Rd merges with Gold Camp Rd. The hike takes you up beside the face of the falls, then back around to another creek and a promontory from which you can view the entire valley.')
 HikePhoto.create(hike_id: helen.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/39787135/extra_large_8ba7cf4cad5e98a67c21013f65544176.jpg', caption: 'From the top of the falls')
 

 dunes = Hike.create(user_id: admin.id, title: 'High Dune Trail', city: 'Mosca', state: 'Colorado', difficulty: 5, length: 3, pet_friendly: true, directions: 'From Mosca take CO-17 North then turn right onto Lane 6 N for 12 miles. Then turn left onto CO-150 N and take that for about 3 miles.', extra_info: 'High Dune trail at the Great Sand Dunes National Monument is not a marked trail.  Make your way there the best you can by following the ridges of the dunes on the way. Dogs are allowed on the trail to High Dune and on the front range of Dunes, but they are not allowed past the highest point on High Dune.')
 HikePhoto.create(hike_id: dunes.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41027933/extra_large_9ec316fcd7de2341541b34c96db4d40e.jpg', caption: 'On top of the Dunes')
 HikePhoto.create(hike_id: dunes.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41027924/extra_large_fc381854f1c8cf54302330ac0e5d4e1d.jpg', caption: 'Mountains from the Dunes')
 HikePhoto.create(hike_id: dunes.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40857015/extra_large_e6686a0ccadc91c95d089299ab5876a2.jpg', caption: 'Mountain view from the top')


 dlt = Hike.create(user_id: admin.id, title: 'Sand Dunes Loop Trail', city: 'Mosca', state: 'Colorado', difficulty: 3, length: 5, pet_friendly: true, directions: 'From Mosca take CO-17 North then turn right onto Lane 6 N for 12 miles. Then turn left onto CO-150 N and take that for about 3 miles.', extra_info: 'Medano Creek is one of the rare creeks in the world where a system of rhythmic waves is created from surging seasonal waters over a smooth creek bed with a steep gradient to give it enough speed. The waters are highest in May and June, but usually almost nonexistent by the Visitor Center by the fall. Snow can still be present in the park into May.')
 HikePhoto.create(hike_id: dlt.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/23108106/extra_large_90f1e67e4ac6515d1aa9015e47a291bf.jpg', caption: 'View of the creek at the beginning of the loop')
 HikePhoto.create(hike_id: dlt.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40823103/extra_large_79c3447caee77aa6b4bd61a2b6ec4182.jpg', caption: 'Sand Dunes Loop Trail')


 sherman = Hike.create(user_id: admin.id, title: 'Mount Sherman', city: 'Leadville', state: 'Colorado', difficulty: 4, length: 5, pet_friendly: true, directions: 'To access this trail, take County Road 18 and, starting at the Leavick Site at around ten miles (16 km) in, there are numerous parking areas with signs. Depending on your car, you can choose to continue up the road, which gets more rugged as it goes. The road is rough, but doable if moving slowly. The hike itself begins at Fourmile Creek Trailhead.', extra_info: 'Mt. Sherman is one of the easiest 14ers and it is full of mining history. Do not attempt to climb the cornice blocking the trail. It’s safest to hike around it to avoid getting injured. As you approach the large abandoned mine, stay climber’s right and then traverse left across the more mild snowfield to gain the ridge.')
 HikePhoto.create(hike_id: sherman.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/38315689/extra_large_5b6d535f9c28b926166ff273dc85fc2e.jpg', caption: 'Mount Sherman')
 HikePhoto.create(hike_id: sherman.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40985088/extra_large_84252ef84e2fe2816faee443d1863851.jpg', caption: 'View from the top')
 

 hagerman = Hike.create(user_id: admin.id, title: 'Hagerman Tunnel Trail', city: 'Leadville', state: 'Colorado', difficulty: 3, length: 6, pet_friendly: true, directions: 'From Leadville, follow signs to Turquoise Lake Recreation Area, travel west on the southern loop around the lake (Lake County Rd 9), and turn left on County Rd 4. Take the Hagerman Pass Road (Forest Service Road 105) 3.75 miles to the parking area.  The trail begins near an interpretive sign on the west side of the road.', extra_info: 'The trail is an old railroad bed with some double track, but mostly single track with some railroad cuts that have collapsed and rotted away making portions of the trail more challenging. This trail tends to be heavily trafficed during the summer season, so arriving early is reccommended.')
 HikePhoto.create(hike_id: hagerman.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40806349/extra_large_fd72c9e4c38b0986f34adcd928e7cbcd.jpg', caption: 'Lake on the trail')
 HikePhoto.create(hike_id: hagerman.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40806345/extra_large_86d832e07fb176f98511f6e240528ac2.jpg', caption: 'Hagerman tunnel')
 HikePhoto.create(hike_id: hagerman.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40806347/extra_large_6db6a74d871c808eaac4329557dc4a48.jpg', caption: 'Douglass City sign on the trail')

 
 turq = Hike.create(user_id: admin.id, title: 'Turquoise Lake Trail', city: 'Leadville', state: 'Colorado', difficulty: 2, length: 11, pet_friendly: true, directions: 'From Leadville head south on Harrison Ave toward W 8th St. Turn right onto W 8th St, then in half a mile turn right onto James St. After that turn left onto McWenthy Dr. In 2.5 miles turn right onto County Rd 4, then follow that for 3 miles.', extra_info: 'Turquoise Lake Trail is a 11 mile moderately trafficked out and back trail located near Leadville, Colorado that features a lake and is good for all skill levels. The trail offers a number of activity options and is best used from April until September. If you go in the fall this is a great hike to see the leaves changing color. Dogs are also able to use this trail but must be kept on leash.')
 HikePhoto.create(hike_id: turq.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40991142/extra_large_a4304bc9c71804eac09d030c7fcdaa41.jpg', caption: 'Leaves changing on the shore')
 HikePhoto.create(hike_id: turq.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/18057817/extra_large_4047245bc5b68e59779f510bcb194679.jpg', caption: 'Turquoise Lake')
 
 vrain = Hike.create(user_id: admin.id, title: 'Saint Vrain Mountain Trail', city: 'Indian Peaks Wilderness', state: 'Colorado', difficulty: 5, length: 8, pet_friendly: false, directions: 'Take Highway 7 to Allenspark and take the Business Loop 7 (which goes through the middle of town) to find CR107. Take CR107 as it winds through the neighborhood for about 1.5 miles and it will turn into Forrest Road 116. Follow 116 for about 1/2 mile more and it will split into two (116.1 and 116.2) keep to the right. There is a sign indicating it is the St Vrain trailhead parking. Parking is small and limited.', extra_info: 'The trail starts in an aspen grove and rises upon a south facing slope in mixed aspens and pines. Shortly after entering the Indian Peaks Wilderness the trail parallels a creek. After a couple small switchbacks temporarily leave the creek, a big switchback carries you up from the stream to where you get your first views of the area. Traversing around the upper basin of the stream, the trail finally crosses the stream and leaves the pines and aspens for firs and spruces. Views out to the plains improve as the trail swings back north and then turns to reach treeline after a short steep switchback. The trail crosses the divide into the Wild Basin drainage and Rocky Mountain National Park with views of peaks defining the basin. After descending briefly into the forested saddle on the east side of St. Vrain Mountain, you leave the trail to climb to the summit. Some cairns define a few routes but there is little difficulty in almost any route chosen that avoids krumholz; in general, once above the trees you will probably travel near the park boundary, which is marked with flexible posts.')
 HikePhoto.create(hike_id: vrain.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/11424425/extra_large_fb126d30ac075c1e0aeead2e7348ba30.jpg', caption: 'St. Vrain Mountain (L), and Meadow Mt. (R)')
 HikePhoto.create(hike_id: vrain.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/39311403/extra_large_6c26ab39b923f81f2e01636b41a03ee1.jpg', caption: 'Saint Vrain Mountain Trail')
 HikePhoto.create(hike_id: vrain.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40744727/extra_large_c32f926cf049d5ee1a7aa0410f932b4e.jpg', caption: 'All the way up')

 devil= Hike.create(user_id: admin.id, title: 'Devils Thumb Pass and King Lake Trail', city: 'Indian Peaks Wilderness', state: 'Colorado', difficulty: 5, length: 17, pet_friendly: true, directions: 'Directions from Eldora: Travel west to the Hessie Townsite on CR #130', extra_info: 'Devils Thumb Pass and King Lake Trail can be a challenging day hike or a perfect multi day backpacking trip in the Indian Peaks Wilderness! This route is great for wildflowers in the spring and home to many moose and elk. Expect incredible views of the surrounding mountains once you get up to the Continental Divide. In the colder months, be sure to use proper gear such as microspikes, as this trail can get icy!')
 HikePhoto.create(hike_id: devil.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/41005112/extra_large_f31c9d5e0f27963f20b673a267d46589.jpg', caption: 'Devils Thumb Lake Trail')
 HikePhoto.create(hike_id: devil.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/20770682/extra_large_126fc982451b38416f28af39d10d74d3.jpg', caption: 'On the trail')
 HikePhoto.create(hike_id: devil.id, img_url: 'https://cdn2.apstatic.com/photos/hike/7034580_medium_1555000563.jpg', caption: 'View of the lake')

 scarp =Hike.create(user_id: admin.id, title: 'Scarp Ridge to 421 Trail Loop', city: 'Crested Butte', state: 'Colorado', difficulty: 3, length: 4, pet_friendly: true, directions: 'After turning off of CO road 12, stay to the left at the fork and head up to Lake Irwin, and then follow the road around the left side of the lake.', extra_info: 'This gorgeous ridge trail offers stunning views and some rigorous hiking. Please note, some users report that an AWD or high-clearance vehicle may be needed to get to the trailhead.')
 HikePhoto.create(hike_id: scarp.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/23482509/extra_large_4e2fe3111c29b3b9f9fd089959117112.jpg', caption: 'Scarp Ridge')
 HikePhoto.create(hike_id: scarp.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40604602/extra_large_3179de39dd7f667ab831101a32d30011.jpg', caption: 'Mt. Emmons from the trail')

 joy = Hike.create(user_id: admin.id, title: 'Oh-Be-Joyful Trail', city: 'Crested Butte', state: 'Colorado', difficulty: 5, length: 14, pet_friendly: true, directions: 'Directions from Crested Butte: Travel a half mile north on Gothic Road to Slate River Road, Forest Road 734, and drive three and a half miles northwest to Oh-Be-Joyful Road', extra_info: 'This route is not open during the winter months due to snow. Trail begins at the Ob-Be-Joyful Trailhead and campground. There are several downed trees from avalanches that you will navigate around but pick up the trail easily. Once you reach the intersection of the Oh-Be-Joyful trail and Blue Lake trail, take a left and head toward Blue Lake. You will gain ~1,000 ft of elevation from this intersection to Blue Lake. There are dispersed camping sites available throughout the trail but space is limited at the lake.')
 HikePhoto.create(hike_id: joy.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/13569647/extra_large_3e79e2623395b78f64c883db14e99e40.jpg', caption: 'Oh-Be-Joyful Trail')
 HikePhoto.create(hike_id: joy.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40815547/extra_large_c012fddce9c71f069b6c49faf5f68f7d.jpg', caption: 'Falls on the trail')
 HikePhoto.create(hike_id: joy.id, img_url: 'https://cdn-assets.alltrails.com/uploads/photo/image/40815430/extra_large_d330abbc527602a6ea3f748bc4a8b7ef.jpg', caption: 'Changing colors in the fall')


 # XXXX = Hike.create(user_id: admin.id, title: '', city: '', state: 'Colorado', difficulty: , length: , pet_friendly: , directions: '', extra_info: '')

# XXXX =HikePhoto.create(hike_id: , img_url: '', caption: '')

puts('done seeding, happy trails!')